### ISSUE TITLE
numpy update causes crash in staging

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-gw#12]
```python
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/app.py", line 35, in <module>
    from ..analysis.queries import *
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 29, in <module>
    from .products import SpectralFitProduct, QueryOutput, QueryProductList, ImageProduct
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/products.py", line 34, in <module>
    from oda_api.api import DispatcherAPI
  File "/src/oda-api/oda_api/api.py", line 13, in <module>
    from gwpy.timeseries.timeseries import TimeSeries
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/timeseries/__init__.py", line 22, in <module>
    from .core import (TimeSeriesBase, TimeSeriesBaseDict, TimeSeriesBaseList)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/timeseries/core.py", line 53, in <module>
    from ..types import Series
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/types/__init__.py", line 31, in <module>
    from . import io
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/types/io/__init__.py", line 22, in <module>
    from . import (  # pylint: disable=unused-import
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/types/io/hdf5.py", line 29, in <module>
    from ...io import (hdf5 as io_hdf5, registry as io_registry)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/gwpy/io/hdf5.py", line 28, in <module>
    import h5py
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/h5py-2.10.0-py3.8-linux-x86_64.egg/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/h5t.pyx", line 293, in init h5py.h5t
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'

```

**Comment by volodymyrss** [comment]
this would seem to suggest that the container https://github.com/oda-hub/dispatcher-container has different versions.
This is possible if gw plugin does not constrain the dependency as it needs it, but other plugins favor another version.

Do you think we could constrain  something here, @dsavchenko ?
We need also a test https://github.com/oda-hub/dispatcher-app/issues/500 for this condition.

**Comment by dsavchenko** [comment]
The problem is caused by the old h5py 
I don't now see the reason its version is so restricted

**Comment by volodymyrss** [comment]
> The problem is caused by the old h5py I don't now see the reason its version is so restricted

could we set a constrain on h5py here? if it conflicts elsewhere we can resolve. but this project here has a h5py version requirement which is not expressed, right?
